//Task:
//T-1
document.write(null||2||undefined);
//T-2
document.write("<br>",alert(1)||2||alert(3))
//T-3
document.write("<br>",1&&null&&2)
//T-4
alert(alert(1)&&2&&alert(3))
document.write("<br>",alert(1)&&alert(3))
